#!/usr/bin/env bash
# 
# Description: start/stop Fusion Middleware WebLogic 11g

# (for Red Hat EL 6)

### BEGIN INIT INFO
# chkconfig: 2345 99 01
# Provides: weblogic_start_stop
# Required-Start: 
# Should-Start: 
# Required-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start Fusion Middleware WebLogic 11g
### END INIT INFO


# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status
. /etc/init.d/functions

# catch mis-use right here at the start
if [  "$1" != "start"  -a  "$1" != "stop" ]; then
    echo "Usage: $0 {start|stop}"
    exit 1
fi

ORACLE_BASE=/opt/oracle
MW_HOME=/opt/oracle/fmw/product/11.1.2
FMWCTLSTR="su - oracle -c $MW_HOME/startFMW.sh"
FMWCTLSTP="su - oracle -c $MW_HOME/stopFMW.sh"
LOCKFILE=/var/lock/subsys/FSWeblogic 

case "$1" in
  start)
    echo
    echo -n $"Starting FMW/WLS 11g: "
    $FMWCTLSTR &
    touch $LOCKFILE
    ;;
  stop)
    echo
    echo -n $"Stopping FMW/WLS 11g: "
    $FMWCTLSTP  
    rm -f $LOCKFILE
    ;;
esac
exit 
